### ISSUE TITLE
Read接口无法获得VLAN信息

### ISSUE THREAD

**Issue by rdcloyi** [hujun-open/etherconn#3]
EtherConn的ReadPktFrom/ReadPkt接口都只返回payload，但不返回以太网帧的VLAN。当EtherConn工作在“default”模式时，上层无法得到VLAN信息，这样在创建返回帧的时候，EtherConn也无法在以太网帧头中创建正确的VLAN信息。希望增加能够直接返回RelayRecieval的Read接口。

**Comment by hujun-open** [comment]
I added it on the roadmap, will address this when I get some time

**Comment by hujun-open** [comment]
just pushed v0.5.0, with following changes:
 - breaking change: change EtherConn.ReadPktFrom and EtherConn.ReadPkt to return remote L2Endpoint;
- breaking change: replace RelayReceival.RemoteMAC to LocalEndpoint/RemoteEndpoint
