### ISSUE TITLE
Any plans for Windows version?

### ISSUE THREAD

**Issue by lonnietc** [hujun-open/etherconn#4]
Hello,

Are there any plans for a version that can be compiled with Golang on Windows?

Thanks

**Comment by hujun-open** [comment]
maybe, depends on the use case, it is not trivial effort, what are you trying to do with etherconn on windows?  why not using linux?

**Comment by lonnietc** [comment]
I want to experiment with possible new protocols at various layers for potential use in a new P2P Balancing Mesh Network that will compile with Go cross-platform to include Windows as well as Linux.

**Comment by hujun-open** [comment]
I added this to roadmap, till I got time for it

**Comment by lonnietc** [comment]
Thanks and I'll look forward to seeing it should you end up with some time available to make it happen.

**Comment by hujun-open** [comment]
In the meantime, I suggest to start with Linux to make sure etherconn is what you want; since etherconn bypass most kernel network stack, which means it doesn't do a lot of networking function like ARP, or using route table to forward a packet, if you need such function you have to do it yourself

**Comment by hujun-open** [comment]
v0.6.0 added support for pcap relay, it supports both windows and linux
